--DROP EXTENSION IF EXISTS pgcrypto;
--CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS administrador CASCADE;
DROP TABLE IF EXISTS gerente CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS subcategoria CASCADE;
DROP TABLE IF EXISTS producto CASCADE;
DROP TABLE IF EXISTS comentario CASCADE;
DROP TABLE IF EXISTS sede CASCADE;
DROP TABLE IF EXISTS catalogo CASCADE;
DROP TABLE IF EXISTS imagen CASCADE;
DROP TABLE IF EXISTS descuento CASCADE;
DROP TABLE IF EXISTS descuento_producto CASCADE;
DROP TABLE IF EXISTS detalle_factura CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS pago CASCADE;

CREATE TABLE usuario
(
    id_usuario SERIAL PRIMARY KEY,

    documento VARCHAR(2) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    nombres VARCHAR(30) NOT NULL,
    apellidos VARCHAR(30) NOT NULL,
    telefono VARCHAR(10),
    direccion VARCHAR(50) NOT NULL,
    cumpleanos DATE,
    nacimiento DATE,
    correo VARCHAR(50) NOT NULL
);

CREATE TABLE administrador
(
    id_adm INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    estado SMALLINT  NOT NULL,
    clave VARCHAR(10) NOT NULL,
    nick VARCHAR(15),
    id_usuario INTEGER NOT NULL,


    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE gerente
(
    id_gerente INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    estado SMALLINT  NOT NULL,
    clave VARCHAR(10) NOT NULL,
    nick VARCHAR(15),
    id_usuario INTEGER NOT NULL,

    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);


CREATE TABLE cliente
(
    id_cliente INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    estado SMALLINT  NOT NULL,
    clave VARCHAR(10) NOT NULL,
    nick VARCHAR(15),
    tarjeta VARCHAR(20),
    id_usuario INTEGER NOT NULL,

    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)

);


CREATE TABLE categoria
(
    id_categoria INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    nombre VARCHAR(15) NOT NULL
);

CREATE TABLE subcategoria
(
    id_subcategoria INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(15) NOT NULL,
    id_categoria INTEGER NOT NULL,

    FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)

);

CREATE TABLE producto(
    codigo_producto INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(30) NOT NULL,
    imagen_url VARCHAR(100) NOT NULL,
    empresa_fabricante VARCHAR(30) NOT NULL,
    descripcion TEXT NOT NULL,
    precio_unitario FLOAT NOT NULL,
    descuento FLOAT NOT NULL,
    iva FLOAT NOT NULL,
    unidades_disponibles INTEGER NOT NULL,
    detalles TEXT NOT NULL,
    id_subcategoria INTEGER NOT NULL,
    FOREIGN KEY (id_subcategoria) REFERENCES subcategoria(id_subcategoria)

);

CREATE TABLE comentario
(
    id_comentario INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    comentario VARCHAR(50) NOT NULL,
    calificacion VARCHAR(2) NOT NULL,
    fecha DATE NOT NULL,
    codigo_producto INTEGER NOT NULL,

    FOREIGN KEY (codigo_producto) REFERENCES producto(codigo_producto)
);

CREATE TABLE sede
(
    id_sede INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    ciudad VARCHAR(10) NOT NULL,
    id_gerente INTEGER NOT NULL,

    FOREIGN KEY (id_gerente) REFERENCES gerente(id_gerente)
);

CREATE TABLE catalogo
(
    id_sede INTEGER NOT NULL,
    codigo_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,

    FOREIGN KEY (id_sede) REFERENCES sede(id_sede),
    FOREIGN KEY (codigo_producto) REFERENCES producto(codigo_producto),

    PRIMARY KEY (id_sede, codigo_producto)
);

CREATE TABLE imagen
(
    numImagen INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    link VARCHAR(100),
    codigo_producto INTEGER NOT NULL,
    FOREIGN KEY (codigo_producto) REFERENCES producto(codigo_producto)
);

CREATE TABLE descuento
(
    id_descuento INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    descripcion VARCHAR(50) NOT NULL,
    descuento INTEGER NOT NULL,
    fechaIni DATE,
    fechaFin DATE
);

CREATE TABLE descuento_producto
(
    id_descuento INTEGER NOT NULL,
    codigo_producto INTEGER NOT NULL,

    FOREIGN KEY (id_descuento) REFERENCES descuento(id_descuento),
    FOREIGN KEY (codigo_producto) REFERENCES producto(codigo_producto),

    PRIMARY KEY (id_descuento, codigo_producto)
);

CREATE TABLE factura
(
    id_factura INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    estado VARCHAR (10) NOT NULL,
    fecha DATE NOT NULL,
    total INTEGER NOT NULL,
    cuotas VARCHAR(3),
    id_cliente INTEGER NOT NULL, 

    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

CREATE TABLE detalle_factura
(
    num_detalle INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cantidad INTEGER NOT NULL,
    precio_actual INTEGER NOT NULL,
    codigo_producto INTEGER NOT NULL,
    id_factura INTEGER NOT NULL,

    FOREIGN KEY (codigo_producto) REFERENCES producto(codigo_producto),
    FOREIGN KEY (id_factura) REFERENCES factura(id_factura)
);

CREATE TABLE pago
(
    num_pago INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    modo VARCHAR(10) NOT NULL,
    monto VARCHAR(10) NOT NULL,
    fecha DATE,
    id_factura INTEGER NOT NULL,

    FOREIGN KEY (id_factura) REFERENCES factura(id_factura)
);


INSERT INTO usuario (documento, numero, nombres, apellidos, telefono, direccion, cumpleanos, nacimiento, correo) VALUES
('CC', 1144189914, 'Esneider Arbey', 'Manzano Arango', '4455971', 'CRA 28C #54-123', '1995-10-18', '1995-10-18', 'esneider.manzano@correounivalle.edu.co'),
('CC', 152399745, 'loquendo', 'Torres Melo', '123654789', 'CRA 28C #54-123', '1995-10-18', '1995-10-18', 'loquendomanzano@yahoo.es'),
('CC', 1234188615, 'samir', 'valencia', '3015489360', 'CRA 41A #54-44', '1997-05-08', '1997-05-08', 'actranniex@outlook.com'),
('CC', 12341886, 'cristian', 'manosalva', '30154893', 'CRA 41 #4-44', '1997-02-08', '1997-02-08', 'sixoble@gmail.com');

INSERT INTO administrador (estado, clave, nick, id_usuario) VALUES (0, 'stemen', 'loquendo', 2);

INSERT INTO gerente (estado, clave, nick, id_usuario) VALUES( 1, 'stemen', 'ranniex', 3);
INSERT INTO gerente (estado, clave, nick, id_usuario) VALUES( 1, 'stemen', 'luisg', 1);

INSERT INTO cliente (estado, clave, nick, id_usuario) VALUES (1,'alix','spartan',4);


INSERT INTO categoria (nombre) VALUES ('Celulares');

INSERT INTO subcategoria (nombre, id_categoria) VALUES('Gama Alta',1), ('Gama Media',1), ('Gama Baja',1);

INSERT INTO producto(nombre, imagen_url, empresa_fabricante, descripcion, precio_unitario, descuento, iva, unidades_disponibles, detalles, id_subcategoria)
    VALUES('Redmi Note 7','url_imagen','Xiaomi','Telefono Android 9',500000.45,0,19,10,'lorem ipsum', 1);

INSERT INTO sede (ciudad, id_gerente) VALUES('Cali', 1);
INSERT INTO sede (ciudad, id_gerente) VALUES('Medellin', 2);
