DROP EXTENSION IF EXISTS pgcrypto;
--CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS administrador;
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    documento VARCHAR(2) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    nombres VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    telefono VARCHAR(10),
    direccion VARCHAR(50) NOT NULL,
    cumpleanos DATE,
    nacimiento DATE,
    correo VARCHAR(50) NOT NULL
);


CREATE TABLE administrador
(
    id serial PRIMARY KEY,
    estado SMALLINT  NOT NULL,
    clave TEXT NOT NULL,
    nick VARCHAR(15),
    usuarioId INTEGER NOT NULL REFERENCES usuario(id)
);

INSERT INTO usuario (documento, numero, nombres, apellidos, telefono, direccion, cumpleanos, nacimiento, correo) VALUES
('CC', 1144189914, 'Esneider Arbey', 'Manzano Arango', '4455971', 'CRA 28C #54-123', '1995-10-18', '1995-10-18', 'esneider.manzano@correounivalle.edu.co'),
('CC', 152399745, 'loquendo', 'Torres Melo', '123654789', 'CRA 28C #54-123', '1995-10-18', '1995-10-18', 'loquendomanzano@yahoo.es');

insert into administrador (estado, clave, nick, usuarioId) values
(0, 'stemen', 'loquendo', 2);