 --NOMBRE: V-ShopBD
--AUTOR: Luis Alberto Gómez
--PROPOSITO: Basé de datos para el proyecto.
--TABLAS: 15 --> [rol, usuario, categoria, subcategoria, producto, comentario, descuento, catalogo_productos, sede, catalogo, factura, 
--               detalle_factura, detalles_del_pago, modo_de_pago, pago].
--Versión: 1.0

--DROP EXTENSION IF EXISTS pgcrypto;
--CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS usuario CASCADE;
--tabla para los usuarios.
CREATE TABLE usuario
(
    id_usuario INTEGER PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY,
    tipo_documento VARCHAR(2) NOT NULL,
    numero_documento VARCHAR(10) NOT NULL,
    nombres VARCHAR(30) NOT NULL,
    apellidos VARCHAR(30) NOT NULL,
    telefono VARCHAR(10),
    direccion VARCHAR(50),
    fecha_de_nacimiento DATE NOT NULL,  
    correo VARCHAR(50),
    estado INTEGER  NOT NULL,--para manejar el borrado logico: 0--> inactivo|1-->activo.
    clave VARCHAR(30) NOT NULL,
    nick VARCHAR(30) UNIQUE NOT NULL,--unico para el registro a la plataforma.
    tipo_usuario VARCHAR(15) NOT NULL--para asignar permisos: Administrador, Gerente, Cliente.
);

--Bloque insert para los usuarios: 1 Administrador | 2 Gerentes | 5 Clientes = 8 Registros. 
INSERT INTO usuario (tipo_documento, numero_documento, nombres, apellidos, telefono, direccion, fecha_de_nacimiento,
                    correo, estado, clave, nick, tipo_usuario) VALUES ('CC','122093205','Esneider Arbey','Manzano Manzano',3137759852,
                                                                       'CR 2C # 71-52','1996-12-23','Esneider@gmail.com',1,'stemen','loquendo','Administrador'),
                                                                      ('CC','146853205','Cristian','Manosalva Beltran',3137527852,
                                                                       'CR 5 # 77-52','1996-12-23','Cristian@gmail.com',1,'rifirafe','rapimen','Gerente'),
                                                                      ('CC','146853205','Samir Farid','Valencia Valencia',3137249852,
                                                                       'CR 1A # 12-11','1998-12-23','Samir@gmail.com',1,'lolero','niñoniña','Gerente'),
                                                                      ('CC','146853205','Siquiere','Prueba Mela',3137527852,
                                                                       'CR 1 # 12-11','1998-12-23','cliente1@gmail.com',1,'contraseña1','cliente1','Gerente'),
                                                                      ('CC','100255678','Gustoso','Prueba Melacosa',3137527852,
                                                                       'CR 2 # 12-11','1998-12-23','cliente2@gmail.com',1,'contraseña2','cliente2','Cliente'),
                                                                      ('TI','146743985','Elber','Gomez Torba',3137527852,
                                                                       'CR 3 # 12-11','1998-12-23','cliente3@gmail.com',1,'contraseña3','cliente3','Cliente'),
                                                                      ('CC','146304855','Elber','gudo grueso',3137527852,
                                                                       'CR 4 # 12-11','1998-12-23','cliente4@gmail.com',1,'contraseña4','cliente4','Cliente'),
                                                                      ('TI','146874395','Aquiles','Clavel Banano',3137527852,
                                                                       'CR 5 # 12-11','1998-12-23','cliente5@gmail.com',1,'contraseña5','cliente5','Cliente');
------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS categoria CASCADE;
--tabla para las categorias.
CREATE TABLE categoria
(
    id_categoria INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria VARCHAR(30) UNIQUE NOT NULL
        );


--Bloque insert para las categorias: 5 Registros. 
INSERT INTO categoria (nombre_categoria) VALUES ('EQUIPOS DE COMPUTO'),
                                                ('DISPOSITIVOS MOVILES'),
                                                ('CONSOLAS DE VIDEO JUEGOS'),
                                                ('SMART WIDGETS'),
                                                ('ZONA MULTIMEDIA');

------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS subcategoria CASCADE;
--tabla para las subcategorias.
CREATE TABLE subcategoria
(
    id_subcategoria INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_subcategoria VARCHAR(50) UNIQUE NOT NULL,
    id_categoria INTEGER NOT NULL,
    FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria) ON DELETE CASCADE
);

--Bloque insert para las subcategorias: 15 Registros. 3 por cada categoria.
INSERT INTO subcategoria (nombre_subcategoria, id_categoria) VALUES('DESKTOP',1),
                                                                               ('GAMER O DE ALTO REDIMIENTO',1),
                                                                               ('PORTATILES',1),
                                                                               ('GAMA ALTA',2),
                                                                               ('GAMA MEDIA',2),
                                                                               ('GAMA BAJA',2),
                                                                               ('CONSOLAS TRADICIONALES',3),
                                                                               ('CONSOLAS PORTATILES',3),
                                                                               ('ARCADES',3),
                                                                               ('SMART TIME',4),
                                                                               ('SMART HOME',4),
                                                                               ('SMART LIVE',4),
                                                                               ('PROYECTORES DE VIDEO',5),
                                                                               ('CONSOLAS DE SONIDO',5),
                                                                               ('SISTEMAS DE GRABACIÓN MULTIMEDIA',5);

--------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS producto CASCADE;
--tabla para los productos.
CREATE TABLE producto
(
    id_producto INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_producto VARCHAR(100) NOT NULL,
    descripcion VARCHAR(2000) NOT NULL,
    marca VARCHAR(20) NOT NULL,
    precio FLOAT NOT NULL,--tipo de dato especial para manejar cantidades monetarias. tambien podria ser DECIMAL.
    id_subcategoria INTEGER NOT NULL,
    estado INTEGER NOT NULL,
    FOREIGN KEY (id_subcategoria) REFERENCES subcategoria(id_subcategoria) ON DELETE CASCADE
);

INSERT INTO producto(nombre_producto,descripcion,marca,precio,id_subcategoria, estado)
	VALUES  ('HP 22-c026la',' Procesador: AMD A9-9425
                              Sistema Operativo: Windows 10 Home
                              Memoria RAM: 4GB
                              Disco Duro: 500 GB
                              Pantalla: 21.5" Pulgadas ','lENOVO','500','1', '1'),
           ('LENOVO - a340',' Procesador: Intel Core I3 8145U 2.1GHz
                              Sistema Operativo: Windows 10 HOME 64 EM
                              Memoria RAM: 4 GB
                              Disco Duro: 1TB
                              Pantalla: 21,5" Pulgadas en Full HD ','HP','500','1', '1'),
            ('HP 22-c016la',' Procesador: Intel Core I3 8130U
                              Sistema Operativo: Windows 10 Home
                              Memoria RAM: 4GB
                              Disco Duro: 1TB
                              Pantalla: 21.5" Pulgadas ','HP','500','1', '1'),
		   ('Acer Nitro 5 AN515','• Procesador: 8ª generación, Intel Core i5+8300H
                                  • Memoria RAM: 4 GB
                                  • Intel Optane: 16 GB
                                  • Disco duro: 1 TB
                                  • Sistema operativo: Windows 10 Home S','acer','500','2', '1'),
           ('HP 15-CX0001LA','• Tamaño pantalla: 15.6"
                              • Resolución: 1920 x 1080
                              • Procesador: Core i5
                              • Memoria RAM: 8 GB
                              • Disco duro: 1TB
                              • Sistema operativo: Windows 10 Home','HP','500','2', '1'),
            ('Legion Y540','• Pantalla: 15.6" antirreflejos FHD 1920 x 1080
                            • Procesador: Intel Core I5-9300H 2.4 GHz (Novena generación)
                            • Memoria RAM: 8 GB
                            • Disco duro: 1TB HDD + 128 SSD
                            • Sistema operativo: Windows 10 Home SL','HP','500','2', '1'),
            ('LENOVO - s340',' Procesador: AMD R5 3500U 2.1GHz
                               Sistema Operativo: Windows 10 Home
                               Memoria RAM: 4GB
                               Disco Duro: Híbrido 1TB HDD + 128GB SSD
                               Pantalla: 14"Pulgadas en HD','lenovo','500','3', '1'),
            ('HP 15-db0009la',' Tarjeta Gráfica: AMD Radeon 530 con 2 GB DDR5 de memoria gráfica dedicada
                                Procesador: AMD R3- 2200U
                                Sistema Operativo: Windows 10 Home
                                Memoria RAM: 8 GB
                                Disco Duro: 1 TB
                                Pantalla: 15 Pulgada','hp','500','3', '1'),
           ('ASUS X507UA',' Procesador: Intel Core i3-7020U
                            Sistema Operativo: Windows 10 (64bit) 
                            Memoria RAM: 8 GB
                            Disco Duro: 1 TB
                            Disco Solido: 128 GB
                            Pantalla: 15,6" Pulgadas','HP','500','3', '1'),
           ('Xiaomi mi 9T','good phone','Xiaomi','300','4','1'),
           ('iPhone 7','iPhone 7
                        Pantalla: 4.7 HD Retina
                        Cámara: 12 Mpx - Frontal 7 Mpx
                        Procesador: A10
                        Sistema Operativo: iOS 10
                        Memoria Interna: 32 GB
                        Batería: Hasta 16 horas
                        RED: 4G','IPHONE','300','4','1'),
           ('SAMSUNG A10','Mejora tus capturas nocturnas mediante el modo de baja luz.
                           Mantente conectado con nuestra batería de 3400 mAh.
                           Reconocimiento facial como método de desbloqueo.','SAMSUNG','300','4','1'),
           ('SAMSUNG A70','Con tu Galaxy A70 vive una experiencia visual que te lleva a descubrir nuevos mundos,
                           gracias a su pantalla maximizada de 6.7 pulgadas, te acerca aún más a las cosas que te gustan,
                           ya que todo cobra vida con la pantalla Infinity-U Display Super AMOLED FHD+.
                           Ya sea que estés transmitiendo contenido o viendo tus programas favoritos,la relación de aspecto
                           expansiva de 20:9','SAMSUNG','300','5','1'),
           ('MOTOROLA One','Triple Cámara captura mejores momentos con enfoque rápido
                            Pantalla ultra amplia de 6.3” para disfrutar más contenidos
                            128GB de almacenamiento Lleva contigo música y películas','MOTOROLA','300','5','1'),
           ('SAMSUNG Galaxy J2','Diseño que realmente brilla. Galaxy J2 Core cuenta con una vívida pantalla qHD de 5.0
                                "para ofrecer cobertura de pantalla grande para una experiencia de visualización más cautivadora.
                                 También viene en una variedad de opciones de color llamativas con una parte posterior
                                 brillante que realmente se destacan para aquellos que quieren hacer una declaración.','SAMSUNG','500','6', '1'),
           ('HUAWEI Y6','Pantalla 6.09" dewdrop 
                         Camara Frontal de 8Mpx con flash frontal 
                         Memoria ROM de 32GB 
                         Emui 9.0 + Andrioid Pie 9 
                         Super sound Mejora el sonido mediante la tecnología Histen','hG','500','6', '1'),
           ('Consola Xbox One','*"La única consola diseñada para jugar los mejores juegos del pasado, el presente y el futuro. Lo mejor en entretenimiento en 4K. Haz que tus juegos y películas cobren vida.
                                 Ya sea que estés disfrutando de tus juegos, mirando tus series favoritas o haciendo streaming de tu juego, Xbox One S ofrece impresionantes gráficos con tecnología HDR, audio de primera calidad y capacidad de juego rápido y confiable con tus amigos. Los beneficios del alto rango dinámico.
                                 Las estaciones dinámicas cambian todo en el festival automotor más importante del mundo. Hazlo solo o únete a otros jugadores para explorar la hermosa Gran Bretaña histórica en un mundo abierto compartido. Colecciona, modifica y maneja más de 450 autos. Corre, entorpece, crea y explora."
                                *Haz streaming de video Ultra HD 4K en Netflix, Amazon y más.
                                *Disfruta de las películas con lujo de detalle gracias al Blu-ray TM4K Ultra HD.
                                *Haz que tus juegos y películas cobren vida con el audio envolvente que ofrecen Dolby Atmos y DTS: X.1
                                *Disfruta de tus aplicaciones favoritas, como YouTube, Spotify y muchas más.
                                *Los juegos digitales te acompañan; juega en cualquier consola Xbox One','MICROSOFT','500','7', '1'),
           ('PS4 Slim','El PlayStation Hits Bundle es el máximo paquete de entretenimiento con 3 fascinantes juegos de Days Gone, Detroit: Become Human, Tom Clancy’s Rainbow Six Siege, y un cupón de 3 meses para PS Plus.
                        La consola PlayStation 4, ahora más liviana y más delgada
                        Tiene disco duro de 1TB para disfrutar los mejores juegos
                        Estos exclusivos juegos te llevarán a viajes increíbles
                        PSHits ofrece poderosos gráficos y alta velocidad
                        Experiencias de juego atrapantes','SONY','500','7', '1'),
           ('Nintendo Switch','A la potencia de una consola doméstica se le une la movilidad de una consola portátil en Nintendo Switch, la nueva generación de Nintendo que ofrece emociones en casa para uno o varios jugadores y la posibilidad de jugar al mismo título donde quieras, cuando quieras y con quien quieras. Ahora Nintendo Switch te permite jugar Mario Kart cuándo,
            dónde y como quieras, tanto con la familia en la pantalla de televisión , como en el parque o en casa de un amigo.'
            ,'NITENDO','500','8', '1'),
           ('Consola De Bolsillo','Marca
                                    by Hyperkin
                                    Modelo
                                    PSP
                                    Tipo de consola
                                    Portátil
                                    Tipo de batería
                                    Ion de litio
                                    Duración de la batería
                                    10 h
                                    Tamaño de la pantalla
                                    4.3 pulgadas','LG','500','8', '1'),
           ('Consola Retro Arcade','Nuevo Producto 16 GB Retro máquina Arcade con 3000 juegos integrados dos libre Gamepad dos controladores ARCADE MINI',
             'LG','500','9', '1'),
           ('S Box 6s Machine','Upgraded HD & Rich Colors - 1280 x 720 HDMI and VGA full high definition, physical
             output resolution is clearer than the old version of Pandora’s Box 4S. Compatible with all HD TV screen, PC',
             'LG','500','9', '1'),  
           ('Reloj SAMSUNG Galaxy Watch','Redes/Bandas: Solo Bluetooth
                                          Conectividad: NFC
                                          Localización: GPS, Glonass, Wi-Fi, Bluetooth v4.2
                                          Sistema Operativo: Tizen
                                          Pantalla: Gorilla Glass 
                                          Velocidad CPU: 1.15GHz Dual-Core
                                          Memoria: RAM (GB) 0.75
                                          Memoria Interna (GB) 4
                                          Memoria Disponible (GB) 1.5','LG','500','10', '1'),
            ('Apple Watch Series 3','GPS, GLONASS, Galileo y QZSS
                                      Altímetro barométrico
                                      Resistente al agua (50 metros)1
                                      Sensor de frecuencia cardiaca
                                      Acelerómetro
                                      Giroscopio
                                      Sensor de luz ambiente
                                      Capacidad de 8 GB
                                    Cubierta posterior de material compuesto','LG','500','10', '1'),
            ('Cámara para interiores K-CRI2','Descarga desde tu smartphone la app "Smart Kalley", configúrala y empieza a utilizar tu cámara rotativa Kalley. Su cobertura de 360º, detector de movimiento y comunicación bidireccional
                                              son algunas de las características de este producto de Smart Home, todo para que tu hogar sea inteligente.
                                              ','LG','500','11', '1'),
             ('Cámara para interiores K-CRI2','Descarga desde tu smartphone la app "Smart Kalley", configúrala y empieza a utilizar tu cámara rotativa Kalley. Su cobertura de 360º, detector de movimiento y comunicación bidireccional
                                              son algunas de las características de este producto de Smart Home, todo para que tu hogar sea inteligente.
                                              ','LG','500','12', '1'),
           ('Cámara para interiores K-CRI2','Descarga desde tu smartphone la app "Smart Kalley", configúrala y empieza a utilizar tu cámara rotativa Kalley. Su cobertura de 360º, detector de movimiento y comunicación bidireccional
                                              son algunas de las características de este producto de Smart Home, todo para que tu hogar sea inteligente.
                                              ','LG','500','13', '1'),
         ('Cámara para interiores K-CRI2','Descarga desde tu smartphone la app "Smart Kalley", configúrala y empieza a utilizar tu cámara rotativa Kalley. Su cobertura de 360º, detector de movimiento y comunicación bidireccional
                                              son algunas de las características de este producto de Smart Home, todo para que tu hogar sea inteligente.
                                              ','LG','500','14', '1'),
                                              ('Cámara para interiores K-CRI2','Descarga desde tu smartphone la app "Smart Kalley", configúrala y empieza a utilizar tu cámara rotativa Kalley. Su cobertura de 360º, detector de movimiento y comunicación bidireccional
                                              son algunas de las características de este producto de Smart Home, todo para que tu hogar sea inteligente.
                                              ','LG','500','15', '1');

-----------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS imagenes CASCADE;
--tabla para los imagen de los productos.
CREATE TABLE imagenes
(
    id_imagen INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_producto INTEGER NOT NULL,
    ruta VARCHAR(200),
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    PRIMARY KEY (id_imagen)
);

INSERT INTO imagenes (id_producto, ruta) VALUES (1,'product-images/1.jpg'),
                                                (2,'product-images/2.jpg'),
                                                (3,'product-images/3.jpg'),
                                                (4,'product-images/4.png'),
                                                (5,'product-images/5.jpg'),
                                                (6,'product-images/6.jpg'),
                                                (7,'product-images/7.jpg'),
                                                (8,'product-images/8.jpg'),
                                                (9,'product-images/9.jpg'),
                                                (10,'product-images/10.jpg'),
                                                (11,'product-images/11.jpg'),
                                                (12,'product-images/12.jpg'),
                                                (13,'product-images/13.jpg'),
                                                (14,'product-images/14.jpg'),
                                                (15,'product-images/15.jpg'),
                                                (16,'product-images/16.jpg'),
                                                (17,'product-images/17.jpg'),
                                                (18,'product-images/18.jpg'),
                                                (19,'product-images/19.webp'),
                                                (20,'product-images/20.jpg'),
                                                (21,'product-images/21.jpg'),
                                                (22,'product-images/22.jpg'),
                                                (23,'product-images/23.jpg'),
                                                (24,'product-images/24.jpg'),
                                                (25,'product-images/25.jpg'),
                                                (26,'product-images/26.jpg'),
                                                (27,'product-images/27.jpg'),
                                                (28,'product-images/28.jpg');

-----------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS comentario CASCADE;
--tabla para los comentarios de los productos.
CREATE TABLE comentario
(
    id_comentario INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    comentario VARCHAR(500) NOT NULL,
    calificacion INTEGER NULL,
    fecha DATE NOT NULL,
    id_producto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE SET NULL
);

INSERT INTO comentario (comentario, calificacion, fecha, id_producto, id_usuario) VALUES
                         ('comentario de prueba', 5, '2019-02-18',1,4),
                         ('comentario de prueba', 4, '2019-02-18',1,5),
                         ('comentario de prueba', 10, '2019-02-18',1,6),
                         ('comentario de prueba', 3, '2019-02-18',2,4),
                         ('comentario de prueba', 8, '2019-02-18',2,5),
                         ('comentario de prueba', 1, '2019-02-18',1,4);

------------------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS descuento CASCADE;
--tabla para los decuentos.
CREATE TABLE descuento
(
    id_descuento INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL,
    descuento FLOAT NOT NULL,--aqui si es decimal, por que hablamos del porcentaje de descuento.
    fecha_inicial DATE NOT NULL,
    fecha_final DATE NOT NULL
);

--Bloque insert para las descuentos: 5 Registros. 
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Sin Descuento', 0.0, '2019-02-18', '3000-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Nacimiento del niño Dios', 0.50, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Dia de la brujitas', 0.25, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Viernes Negro', 0.50, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Remate Anual', 0.75, '2019-02-18', '2019-02-19');
------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS catalogo CASCADE;
--tabla para los catalogos.
CREATE TABLE catalogo
(
    id_catalogo INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ciudad VARCHAR(30) UNIQUE NOT NULL,
    id_gerente INTEGER,--tiene un gerente.
    nombre_catalogo VARCHAR(30) UNIQUE NOT NULL,
    estado INTEGER NOT NULL,
    FOREIGN KEY (id_gerente) REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

INSERT INTO catalogo (ciudad, id_gerente, nombre_catalogo, estado) VALUES ('Santiago de Cali', 2,'V-Shop Cali',1),
                                                                            ('Medellín', 3,'V-Shop Medellin',1);

------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS inventario_catalogo_productos CASCADE;
--tabla para mostra los productos pertenecientes a un catalogo.
CREATE TABLE inventario_catalogo_productos
(
    id_producto INTEGER NOT NULL,
    cantidad_en_inventario INTEGER NOT NULL,--cantidad de productos disponibles en la tienda.
    id_descuento INTEGER NOT NULL,--relaciona el producto con el descuento.
    id_catalogo INTEGER NOT NULL,
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    FOREIGN KEY (id_descuento) REFERENCES descuento (id_descuento) ON DELETE SET DEFAULT ,
    FOREIGN KEY (id_catalogo) REFERENCES catalogo(id_catalogo) ON DELETE CASCADE,
    PRIMARY KEY(id_catalogo, id_producto)
);


INSERT INTO inventario_catalogo_productos (id_producto,
                                           cantidad_en_inventario,
                                           id_descuento,
                                           id_catalogo) VALUES
                                          (1, 50,1,1),
                                          (2, 50,1,1),
                                          (3, 50,1,1),
                                          (4, 50,1,1),
                                          (5, 50,1,1),
                                          (6, 50,1,1),
                                          (7, 50,1,1),
                                          (8, 50,1,1),
                                          (9, 50,1,1),
                                          (10, 50,1,1),
                                          (11, 50,1,1),
                                          (12, 50,1,1),
                                          (13, 50,1,1),
                                          (14, 50,1,1),
                                          (15, 50,1,1),
                                          (16, 50,1,1),
                                          (17, 50,1,1),
                                          (18, 50,1,1),
                                          (19, 50,1,1),
                                          (20, 50,1,1),
                                          (21, 50,1,1),
                                          (22, 50,1,1),
                                          (23, 50,1,1),
                                          (24, 50,1,1),
                                          (25, 50,1,1),
                                          (26, 50,1,1),
                                          (27, 50,1,1),
                                          (28, 50,1,1),
                                          (1, 50,1,2),
                                          (2, 50,1,2),
                                          (3, 50,1,2),
                                          (4, 50,1,2),
                                          (5, 50,1,2),
                                          (6, 50,1,2),
                                          (7, 50,1,2),
                                          (8, 50,1,2),
                                          (9, 50,1,2),
                                          (10, 50,1,2),
                                          (11, 50,1,2),
                                          (12, 50,1,2),
                                          (13, 50,1,2),
                                          (14, 50,1,2),
                                          (15, 50,1,2),
                                          (16, 50,1,2),
                                          (17, 50,1,2),
                                          (18, 50,1,2),
                                          (19, 50,1,2),
                                          (20, 50,1,2),
                                          (21, 50,1,2),
                                          (22, 50,1,2),
                                          (23, 50,1,2),
                                          (24, 50,1,2),
                                          (25, 50,1,2),
                                          (26, 50,1,2),
                                          (27, 50,1,2),
                                          (28, 50,1,2);

--------------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS factura CASCADE;
--tabla para las facturas.
CREATE TABLE factura
(
    id_factura INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    id_cliente INTEGER NOT NULL, 
    id_catalogo INTEGER NOT NULL,
    id_descuento INTEGER,
    total FLOAT NOT NULL,--tipo de dato especial para manejar cantidades monetarias. También podria ser DECIMAL.
    FOREIGN KEY (id_cliente) REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (id_catalogo) REFERENCES catalogo(id_catalogo) ON DELETE CASCADE
);

INSERT INTO factura (fecha, id_cliente,id_catalogo, id_descuento, total) VALUES
                                          ('2019/01/19', 4,1,NULL,800),
                                          ('2019/02/19', 5,1,NULL,1200),
                                          ('2019/03/19', 6,1,NULL,2800),
                                          ('2019/04/19', 7,1,NULL,4500),
                                          ('2019/05/19', 8,1,NULL,3800);

--------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS detalle_factura CASCADE;
--tabla para mostrar la informacion de la compra: producto,cantidad,descuento.
CREATE TABLE detalle_factura
(
    num_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_factura INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    id_catalogo INTEGER NOT NULL,
    cantidad_comprada INTEGER NOT NULL,
    descuento FLOAT NOT NULL,
    precio_actual FLOAT NOT NULL,--precio calculado por el precio del producto y la cantidad. ya viene con el decuento si lo tiene.
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    FOREIGN KEY (id_factura) REFERENCES factura(id_factura) ON DELETE CASCADE,
    PRIMARY KEY(num_detalle,id_factura)--cada atributo detalle es unico, y depende de la factura.
);

    INSERT INTO detalle_factura (id_factura,id_producto,id_catalogo ,cantidad_comprada,descuento, precio_actual) VALUES
                                          (1,1,1,1,0,300),
                                          (1,2,1,1,0,500),
                                          (2,1,1,1,0,300),
                                          (2,2,2,1,0,300),
                                          (3,1,2,1,0,300);
---------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pago CASCADE;
--tabla para manejar la información de los pagos.
CREATE TABLE pago
(
    num_pago INTEGER  GENERATED BY DEFAULT AS IDENTITY, 
    id_factura INTEGER NOT NULL,
    modo_de_pago VARCHAR(30) NOT NULL,
	banco_entidad VARCHAR(50) NOT NULL,
    numero_tarjeta_cuenta INTEGER NOT NULL,
    monto_del_pago FLOAT NOT NULL,
    cuotas INTEGER NOT NULL,
    FOREIGN KEY (id_factura) REFERENCES factura(id_factura) ON DELETE CASCADE,
    PRIMARY KEY(num_pago,id_factura)
);

  INSERT INTO pago (id_factura,modo_de_pago, banco_entidad,
  numero_tarjeta_cuenta, monto_del_pago, cuotas) VALUES
                                          (1,'Contado','BBVA',1231254758, 800, 1),
                                          (2,'DIFERIDO','COLPATRIA',1216754758, 800, 3);

--Bloque insert para los productos: 100 Registros. 7 en 3 subcategorias y 5 en 1 y 6 en la otra. por categoria.
--INSERT INTO producto (nombre_producto, linkimagen, descripcion, marca, precio, id_subcategoria) VALUES ()

