--NOMBRE: V-ShopBD
--AUTOR: Luis Alberto Gómez
--PROPOSITO: Basé de datos para el proyecto.
--TABLAS: 15 --> [rol, usuario, categoria, subcategoria, producto, comentario, descuento, catalogo_productos, sede, catalogo, factura, 
--               detalle_factura, detalles_del_pago, modo_de_pago, pago].
--Versión: 1.0

--DROP EXTENSION IF EXISTS pgcrypto;
--CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS usuario CASCADE;
--tabla para los usuarios.
CREATE TABLE usuario
(
    id_usuario INTEGER PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY,
    tipo_documento VARCHAR(2) NOT NULL,
    numero_documento VARCHAR(10) NOT NULL,
    nombres VARCHAR(30) NOT NULL,
    apellidos VARCHAR(30) NOT NULL,
    telefono VARCHAR(10),
    direccion VARCHAR(50),
    fecha_de_nacimiento DATE NOT NULL,  
    correo VARCHAR(50),
    estado INTEGER  NOT NULL,--para manejar el borrado logico: 0--> inactivo|1-->activo.
    clave VARCHAR(30) NOT NULL,
    nick VARCHAR(30) UNIQUE NOT NULL,--unico para el registro a la plataforma.
    tipo_usuario VARCHAR(15) NOT NULL--para asignar permisos: Administrador, Gerente, Cliente.
);

--Bloque insert para los usuarios: 1 Administrador | 2 Gerentes | 5 Clientes = 8 Registros. 
INSERT INTO usuario (tipo_documento, numero_documento, nombres, apellidos, telefono, direccion, fecha_de_nacimiento,
                    correo, estado, clave, nick, tipo_usuario) VALUES ('CC','122093205','Esneider Arbey','Manzano Manzano',3137759852,
                                                                       'CR 2C # 71-52','1996-12-23','Esneider@gmail.com',1,'stemen','loquendo','Administrador'),
                                                                      ('CC','146853205','Cristian','Manosalva Beltran',3137527852,
                                                                       'CR 5 # 77-52','1996-12-23','Cristian@gmail.com',1,'rifirafe','rapimen','Gerente'),
                                                                      ('CC','146853205','Samir Farid','Valencia Valencia',3137249852,
                                                                       'CR 1A # 12-11','1998-12-23','Samir@gmail.com',1,'lolero','niñoniña','Gerente'),
                                                                      ('CC','146853205','Siquiere','Prueba Mela',3137527852,
                                                                       'CR 1 # 12-11','1998-12-23','cliente1@gmail.com',1,'contraseña1','cliente1','Gerente'),
                                                                      ('CC','100255678','Gustoso','Prueba Melacosa',3137527852,
                                                                       'CR 2 # 12-11','1998-12-23','cliente2@gmail.com',1,'contraseña2','cliente2','Cliente'),
                                                                      ('TI','146743985','Elber','Gomez Torba',3137527852,
                                                                       'CR 3 # 12-11','1998-12-23','cliente3@gmail.com',1,'contraseña3','cliente3','Cliente'),
                                                                      ('CC','146304855','Elber','gudo grueso',3137527852,
                                                                       'CR 4 # 12-11','1998-12-23','cliente4@gmail.com',1,'contraseña4','cliente4','Cliente'),
                                                                      ('TI','146874395','Aquiles','Clavel Banano',3137527852,
                                                                       'CR 5 # 12-11','1998-12-23','cliente5@gmail.com',1,'contraseña5','cliente5','Cliente');
------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS categoria CASCADE;
--tabla para las categorias.
CREATE TABLE categoria
(
    id_categoria INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria VARCHAR(30) UNIQUE NOT NULL,
    linkimagen VARCHAR(100)--tiene una imagen para reconocerla.
    );


--Bloque insert para las categorias: 5 Registros. 
INSERT INTO categoria (nombre_categoria, linkimagen) VALUES ('EQUIPOS DE COMPUTO', NULL),
                                                ('DISPOSITIVOS MOVILES', NULL),
                                                ('CONSOLAS DE VIDEO JUEGOS', NULL),
                                                ('SMART WIDGETS', NULL),
                                                ('ZONA MULTIMEDIA', NULL);

------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS subcategoria CASCADE;
--tabla para las subcategorias.
CREATE TABLE subcategoria
(
    id_subcategoria INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_subcategoria VARCHAR(50) UNIQUE NOT NULL,
    linkimagen VARCHAR(100),--tiene una imagen para reconocerla.
    id_categoria INTEGER NOT NULL,
    FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria) ON DELETE CASCADE
);

--Bloque insert para las subcategorias: 15 Registros. 3 por cada categoria.
INSERT INTO subcategoria (nombre_subcategoria, linkimagen, id_categoria) VALUES('DESKTOP',NULL,1),
                                                                               ('GAMER O DE ALTO REDIMIENTO',NULL,1),
                                                                               ('PORTATILES',NULL,1),
                                                                               ('GAMA ALTA',NULL,2),
                                                                               ('GAMA MEDIA',NULL,2),
                                                                               ('GAMA BAJA',NULL,2),
                                                                               ('CONSOLAS TRADICIONALES',NULL,3),
                                                                               ('CONSOLAS PORTATILES',NULL,3),
                                                                               ('ARCADES',NULL,3),
                                                                               ('SMART TIME',NULL,4),
                                                                               ('SMART HOME',NULL,4),
                                                                               ('SMART LIVE',NULL,4),
                                                                               ('PROYECTORES DE VIDEO',NULL,5),
                                                                               ('CONSOLAS DE SONIDO',NULL,5),
                                                                               ('SISTEMAS DE GRABACIÓN MULTIMEDIA',NULL,5);

--------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS producto CASCADE;
--tabla para los productos.
CREATE TABLE producto
(
    id_producto INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_producto VARCHAR(20) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    marca VARCHAR(20) NOT NULL,
    precio FLOAT NOT NULL,--tipo de dato especial para manejar cantidades monetarias. tambien podria ser DECIMAL.
    id_subcategoria INTEGER NOT NULL,
    FOREIGN KEY (id_subcategoria) REFERENCES subcategoria(id_subcategoria) ON DELETE CASCADE
);

INSERT INTO producto(nombre_producto,descripcion,marca,precio,id_subcategoria)
	VALUES('Xiaomi mi 9T','good phone','Xiaomi','300','5'),
		('LG UHD','good tv','LG','500','11');

-----------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS imagenes CASCADE;
--tabla para los imagen de los productos.
CREATE TABLE imagenes
(
    id_imagen INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_producto INTEGER NOT NULL,
    ruta VARCHAR(200),
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    PRIMARY KEY (id_imagen)
);

-----------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS comentario CASCADE;
--tabla para los comentarios de los productos.
CREATE TABLE comentario
(
    id_comentario INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    comentario VARCHAR(50) NOT NULL,
    calificacion VARCHAR(2) NOT NULL,
    fecha DATE NOT NULL,
    id_producto INTEGER NOT NULL,
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE
);
------------------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS descuento CASCADE;
--tabla para los decuentos.
CREATE TABLE descuento
(
    id_descuento INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL,
    descuento FLOAT NOT NULL,--aqui si es decimal, por que hablamos del porcentaje de descuento.
    fecha_inicial DATE NOT NULL,
    fecha_final DATE NOT NULL
);

--Bloque insert para las descuentos: 5 Registros. 
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Sin Descuento', 0.0, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Nacimiento del niño Dios', 0.50, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Dia de la brujitas', 0.25, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Viernes Negro', 0.50, '2019-02-18', '2019-02-19');
INSERT INTO descuento (descripcion, descuento, fecha_inicial, fecha_final) VALUES ('Remate Anual', 0.75, '2019-02-18', '2019-02-19');
------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS catalogo CASCADE;
--tabla para los catalogos.
CREATE TABLE catalogo
(
    id_catalogo INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ciudad VARCHAR(30) UNIQUE NOT NULL,
    id_gerente INTEGER NOT NULL,--tiene un gerente.
    nombre_catalogo VARCHAR(30) UNIQUE NOT NULL,
    FOREIGN KEY (id_gerente) REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

INSERT INTO catalogo (ciudad, id_gerente, nombre_catalogo) VALUES ('Santiago de Cali', 2,'V-Shop Cali'),
                                                                  ('Medellín', 3,'V-Shop Medellin');

------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS inventario_catalogo_productos CASCADE;
--tabla para mostra los productos pertenecientes a un catalogo.
CREATE TABLE inventario_catalogo_productos
(
    id_producto INTEGER NOT NULL,
    cantidad_en_inventario INTEGER NOT NULL,--cantidad de productos disponibles en la tienda.
    id_descuento INTEGER NOT NULL,--relaciona el producto con el descuento.
    id_catalogo INTEGER NOT NULL,
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    FOREIGN KEY (id_descuento) REFERENCES descuento (id_descuento) ON DELETE CASCADE,
    FOREIGN KEY (id_catalogo) REFERENCES catalogo(id_catalogo) ON DELETE CASCADE,
    PRIMARY KEY(id_catalogo, id_producto)
);
--------------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS factura CASCADE;
--tabla para las facturas.
CREATE TABLE factura
(
    id_factura INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    id_cliente INTEGER NOT NULL, 
    id_catalogo INTEGER NOT NULL,
    total FLOAT NOT NULL,--tipo de dato especial para manejar cantidades monetarias. También podria ser DECIMAL.
    FOREIGN KEY (id_cliente) REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (id_catalogo) REFERENCES catalogo(id_catalogo) ON DELETE CASCADE
);
--------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS detalle_factura CASCADE;
--tabla para mostrar la informacion de la compra: producto,cantidad,descuento.
CREATE TABLE detalle_factura
(
    num_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_factura INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad_comprada INTEGER NOT NULL,
    precio_actual FLOAT NOT NULL,--precio calculado por el precio del producto y la cantidad. ya viene con el decuento si lo tiene.
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE CASCADE,
    FOREIGN KEY (id_factura) REFERENCES factura(id_factura) ON DELETE CASCADE,
    PRIMARY KEY(num_detalle,id_factura)--cada atributo detalle es unico, y depende de la factura.
    );
---------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pago CASCADE;
--tabla para manejar la información de los pagos.
CREATE TABLE pago
(
    num_pago INTEGER  GENERATED BY DEFAULT AS IDENTITY,
    id_factura INTEGER NOT NULL,
    modo_de_pago VARCHAR(30) NOT NULL,
	banco_entidad VARCHAR(50) NOT NULL,
    numero_tarjeta_cuenta INTEGER NOT NULL,
    monto_del_pago MONEY NOT NULL,
    cuotas INTEGER NOT NULL,
    FOREIGN KEY (id_factura) REFERENCES factura(id_factura) ON DELETE CASCADE,
    PRIMARY KEY(num_pago,id_factura)
);

--Bloque insert para los productos: 100 Registros. 7 en 3 subcategorias y 5 en 1 y 6 en la otra. por categoria.
--INSERT INTO producto (nombre_producto, linkimagen, descripcion, marca, precio, id_subcategoria) VALUES ()


